ffmpeg -i ACTION1.WAV  -codec:a libmp3lame -qscale:a 2 ACTION1.MP3
ffmpeg -i ACTION2.WAV  -codec:a libmp3lame -qscale:a 2 ACTION2.MP3
ffmpeg -i ACTION3.WAV  -codec:a libmp3lame -qscale:a 2 ACTION3.MP3
ffmpeg -i CHAP1.WAV    -codec:a libmp3lame -qscale:a 2 CHAP1.MP3  
ffmpeg -i CHAP2CON.WAV -codec:a libmp3lame -qscale:a 2 CHAP2CON.MP3
ffmpeg -i CHAP2WAR.WAV -codec:a libmp3lame -qscale:a 2 CHAP2WAR.MP3
ffmpeg -i CHAP2WIZ.WAV -codec:a libmp3lame -qscale:a 2 CHAP2WIZ.MP3
ffmpeg -i CHAP3.WAV    -codec:a libmp3lame -qscale:a 2 CHAP3.MP3  
ffmpeg -i CHAP4.WAV    -codec:a libmp3lame -qscale:a 2 CHAP4.MP3  
ffmpeg -i CHAP5.WAV    -codec:a libmp3lame -qscale:a 2 CHAP5.MP3  
ffmpeg -i CHAP6.WAV    -codec:a libmp3lame -qscale:a 2 CHAP6.MP3  
ffmpeg -i CHAP7.WAV    -codec:a libmp3lame -qscale:a 2 CHAP7.MP3  
ffmpeg -i CHAP8.WAV    -codec:a libmp3lame -qscale:a 2 CHAP8.MP3  
ffmpeg -i CHAP9.WAV    -codec:a libmp3lame -qscale:a 2 CHAP9.MP3  
ffmpeg -i CHAPA.WAV    -codec:a libmp3lame -qscale:a 2 CHAPA.MP3  
ffmpeg -i CHAPB.WAV    -codec:a libmp3lame -qscale:a 2 CHAPB.MP3  
ffmpeg -i CREDITS.WAV  -codec:a libmp3lame -qscale:a 2 CREDITS.MP3
ffmpeg -i SHELL.WAV    -codec:a libmp3lame -qscale:a 2 SHELL.MP3  
ffmpeg -i SUB1.WAV     -codec:a libmp3lame -qscale:a 2 SUB1.MP3   
ffmpeg -i SUB2.WAV     -codec:a libmp3lame -qscale:a 2 SUB2.MP3   
ffmpeg -i SUB3.WAV     -codec:a libmp3lame -qscale:a 2 SUB3.MP3   
ffmpeg -i TITLE.WAV    -codec:a libmp3lame -qscale:a 2 TITLE.MP3  
ffmpeg -i TOWN1.WAV    -codec:a libmp3lame -qscale:a 2 TOWN1.MP3  
ffmpeg -i TOWN2.WAV    -codec:a libmp3lame -qscale:a 2 TOWN2.MP3  
ffmpeg -i TOWN3.WAV    -codec:a libmp3lame -qscale:a 2 TOWN3.MP3  
ffmpeg -i WANDER1.WAV  -codec:a libmp3lame -qscale:a 2 WANDER1.MP3
ffmpeg -i WANDER2.WAV  -codec:a libmp3lame -qscale:a 2 WANDER2.MP3
ffmpeg -i WANDER3.WAV  -codec:a libmp3lame -qscale:a 2 WANDER3.MP3
ffmpeg -i WANDER4.WAV  -codec:a libmp3lame -qscale:a 2 WANDER4.MP3